"""Menu UI API."""

from __future__ import annotations

from components.ui.src.menu import (
    BOARD_COMMAND_LABELS,
    MenuItem,
    active_job_for_slot,
    clamp_index,
    clamp_menu_scroll,
    command_preview,
    disabled_reason,
    display_job_for_item,
    item_enabled,
    item_job_slot,
    job_for_item,
    list_scroll,
    menu_rows,
    move_index,
    move_selection,
    nearest_enabled_selection,
    normalize_selection,
    selected_action_guard,
    selected_action_plan,
    selected_menu_row,
    sync_menu_selection,
    wrapped_menu_rows,
)

__all__ = [
    "BOARD_COMMAND_LABELS",
    "MenuItem",
    "active_job_for_slot",
    "clamp_index",
    "clamp_menu_scroll",
    "command_preview",
    "disabled_reason",
    "display_job_for_item",
    "item_enabled",
    "item_job_slot",
    "job_for_item",
    "list_scroll",
    "menu_rows",
    "move_index",
    "move_selection",
    "nearest_enabled_selection",
    "normalize_selection",
    "selected_action_guard",
    "selected_action_plan",
    "selected_menu_row",
    "sync_menu_selection",
    "wrapped_menu_rows",
]
