"""Host field and remote draft policy API."""

from __future__ import annotations

from components.host_config.api.host_fields import (
    BoardHostFieldService,
    BuildHostFieldService,
    board_host_field_service,
    build_host_field_service,
)
from components.host_config.src.fields import (
    add_remote_action_disabled_reason,
    add_remote_action_enabled,
    apply_board_host_direct_copy_toggle_for_config,
    apply_board_host_inline_field_update_for_config,
    apply_remote_draft_create_for_config,
    apply_remote_inline_field_update_for_config,
    apply_remote_labeled_field_update_for_config,
    apply_remote_projects_dir_selection_for_config,
    available_board_type_options,
    board_host_connection_reset_needed,
    board_host_field_disabled_reason,
    board_host_field_enabled,
    board_host_field_hint,
    board_host_fields,
    configuration_screen_key_action,
    host_field_row_model,
    host_profile_count_label,
    host_profile_page_scroll,
    host_profile_row_model,
    next_board_type_value,
    next_direct_copy_value,
    normalize_board_host_field_value,
    normalize_remote_field_value,
    remote_connection_reset_needed,
    remote_draft_action_model,
    remote_draft_actions,
    remote_draft_enter_action_for_config,
    remote_draft_for_config,
    remote_field_disabled_reason,
    remote_field_disabled_reason_for_config,
    remote_field_enabled,
    remote_field_enabled_for_config,
    remote_field_hint,
    remote_fields,
)

__all__ = [
    "BoardHostFieldService",
    "BuildHostFieldService",
    "add_remote_action_disabled_reason",
    "add_remote_action_enabled",
    "apply_board_host_direct_copy_toggle_for_config",
    "apply_board_host_inline_field_update_for_config",
    "apply_remote_draft_create_for_config",
    "apply_remote_inline_field_update_for_config",
    "apply_remote_labeled_field_update_for_config",
    "apply_remote_projects_dir_selection_for_config",
    "available_board_type_options",
    "board_host_connection_reset_needed",
    "board_host_field_disabled_reason",
    "board_host_field_enabled",
    "board_host_field_hint",
    "board_host_fields",
    "board_host_field_service",
    "build_host_field_service",
    "configuration_screen_key_action",
    "host_field_row_model",
    "host_profile_count_label",
    "host_profile_page_scroll",
    "host_profile_row_model",
    "next_board_type_value",
    "next_direct_copy_value",
    "normalize_board_host_field_value",
    "normalize_remote_field_value",
    "remote_connection_reset_needed",
    "remote_draft_action_model",
    "remote_draft_actions",
    "remote_draft_enter_action_for_config",
    "remote_draft_for_config",
    "remote_field_disabled_reason",
    "remote_field_disabled_reason_for_config",
    "remote_field_enabled",
    "remote_field_enabled_for_config",
    "remote_field_hint",
    "remote_fields",
]
