"""Project field and target policy API."""

from __future__ import annotations

from components.project_config.api.project_fields import ProjectFieldService, project_field_service
from components.project_config.api.settings_policy import (
    ProjectSettingsPolicyService,
    project_settings_policy_service,
)
from components.project_config.api.target_policy import (
    TargetSelectionPolicyService,
    target_selection_policy_service,
)
from components.project_config.src.fields import (
    apply_active_project_file_selection_for_config,
    apply_active_project_settings_field_for_config,
    apply_project_inline_field_update_for_config,
    build_target_action_description,
    build_target_action_label,
    next_parameter_value,
    normalize_project_field_value,
    ordered_targets,
    ordered_targets_for_text,
    project_dir_field_update,
    project_docker_image_update_needed,
    project_field_disabled_reason,
    project_field_disabled_reason_for_config,
    project_field_enabled,
    project_field_enabled_for_config,
    project_field_enter_action_for_config,
    project_field_hint,
    project_field_hint_for_config,
    project_field_value,
    project_is_active,
    project_is_active_for_config,
    project_preflight_reset_needed,
    project_profile_row_model,
    project_runtime_reload_needed,
    selected_targets_from_text,
    settings_action_description,
    settings_action_label,
    target_actions,
    target_display_text,
    target_text_for_selection,
    toggle_target_selection,
)

__all__ = [
    "ProjectFieldService",
    "ProjectSettingsPolicyService",
    "TargetSelectionPolicyService",
    "apply_active_project_file_selection_for_config",
    "apply_active_project_settings_field_for_config",
    "apply_project_inline_field_update_for_config",
    "build_target_action_description",
    "build_target_action_label",
    "next_parameter_value",
    "normalize_project_field_value",
    "ordered_targets",
    "ordered_targets_for_text",
    "project_dir_field_update",
    "project_docker_image_update_needed",
    "project_field_disabled_reason",
    "project_field_disabled_reason_for_config",
    "project_field_enabled",
    "project_field_enabled_for_config",
    "project_field_enter_action_for_config",
    "project_field_hint",
    "project_field_hint_for_config",
    "project_field_value",
    "project_field_service",
    "project_is_active",
    "project_is_active_for_config",
    "project_preflight_reset_needed",
    "project_profile_row_model",
    "project_runtime_reload_needed",
    "project_settings_policy_service",
    "selected_targets_from_text",
    "settings_action_description",
    "settings_action_label",
    "target_actions",
    "target_display_text",
    "target_text_for_selection",
    "target_selection_policy_service",
    "toggle_target_selection",
]
